{
  "timestamp": "2025-06-30T19:08:42.344661",
  "api_status": false,
  "streamlit_status": false,
  "api_data": null,
  "errors": [
    "API error: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/bot_status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f026f395930>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "Streamlit error: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f026f396110>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  ]
}